# Generated by Django 4.0.3 on 2022-04-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empregos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referencias',
            new_name='Referencia',
        ),
    ]
