# Generated by Django 4.0.3 on 2022-04-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregos', '0002_rename_referencias_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprego',
            name='status',
            field=models.CharField(choices=[('C', 'Em criação'), ('AA', 'Aguardando aprovação'), ('F', 'Finalizado')], default='C', max_length=2),
        ),
    ]
