# Generated by Django 4.0.3 on 2022-04-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregos', '0003_alter_emprego_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprego',
            name='arquivo_final',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
