# Generated by Django 4.0.3 on 2022-04-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregos', '0004_emprego_arquivo_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprego',
            name='arquivo_final',
            field=models.FileField(null=True, upload_to='arquivos'),
        ),
    ]
